import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

const fontStyle = Noto_Sans_Thai({
  weight: ["100", "200", "300", "400", "500", "600"],
  display: "swap",
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className={fontStyle.className}>{children}</body>
    </html>
  );
}
