import type { Metadata } from "next";
import Sidebar from "../components/navbar/sidebar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "หน้าหลัก",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense fallback="Loading">
        <main className="flex">
            <Sidebar />
          <section className="shrink w-full">
            {children}
          </section>
        </main>
      </Suspense>
    </>
  );
}
