import type { Metadata } from "next";
import Sidebar from "../components/navbar/sidebar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "ลงชื่อเข้าใช้",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Suspense fallback="Loading">
        <main className="flex min-h-screen flex-row flex-wrap items-center">
            <Sidebar />
          <section className="flex flex-col items-center w-2/4 max-md:w-full h-full justify-center">
            {children}
          </section>
        </main>
      </Suspense>
    </>
  );
}
