import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ลงชื่อเข้าใช้",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-row flex-wrap items-center justify-between p-10">
          <section className="flex flex-col items-center w-2/4 h-full">
            <div className="z-10 max-w-5xl w-full items-center justify-center font-mono text-sm lg:flex">
              <Image
                src="/RMUTT.png"
                alt="RMUTT Logo"
                width={550}
                height={187}
              />
            </div>
          </section>
          <section className="flex flex-col items-center w-2/4 max-md:w-full h-full justify-center">
            <div 
              className="w-3/6 p-10 rounded-md dark:border-neutral-800 dark:bg-zinc-200/30 dark:from-inherit 
                  max-xl:w-full max-md:border-none max-md:rounded-none max-md:p-0 max-md:bg-transparent max-md:backdrop-blur-none max-md:dark:bg-transparent max-md:dark:backdrop-blur-none"
            >
              {children}
            </div>
          </section>
        </main>
      </body>
    </html>
  );
}
