import type { Metadata } from "next";
import Image from "next/image";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "ลงชื่อเข้าใช้",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="flex min-h-screen flex-row flex-wrap items-center justify-between bg-forest-green-200 max-xl:bg-white max-md:px-5">
        <section className="flex flex-col items-center w-2/4 h-screen max-lg:hidden">
          <div className="z-10 max-w-5xl w-full h-full items-center justify-center font-mono text-sm lg:flex ">
            <Image
              src="/screen-login.jpg"
              alt="RMUTT"
              width={500}
              height={500}
              priority={true}
              className="rounded-lg object-cover w-full h-full"
            />
          </div>
        </section>
        <section className="flex flex-col items-center w-2/4 max-md:w-full h-full justify-center max-lg:w-full">
          <div
            className="w-3/6 p-10 rounded-md dark:bg-zinc-50 dark:from-inherit
                  max-2xl:w-4/6 border-1 dark:border-stone-300
                  max-xl:w-full max-xl:border-none max-md:rounded-none max-md:p-0 max-xl:bg-transparent max-md:backdrop-blur-none max-xl:dark:bg-transparent max-md:dark:backdrop-blur-none"
          >
            <Image
              src={process.env.NEXT_PUBLIC_APP_LOGO!}
              alt="การยางแห่งประเทศไทย"
              width={150}
              height={150}
              priority={true}
              className="mb-10"
            />
            <Suspense fallback="Loading">{children}</Suspense>
          </div>
        </section>
      </main>
    </>
  );
}
