import type { Metadata } from "next";
import Image from "next/image";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "ลงชื่อเข้าใช้",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="flex min-h-screen flex-row flex-wrap items-center justify-between p-10">
        <section className="flex flex-col items-center w-2/4 h-full">
          <div className="z-10 max-w-5xl w-full items-center justify-center font-mono text-sm lg:flex">
            <Image src="/RMUTT.png" alt="RMUTT" width={500} height={500} priority={true} />
          </div>
        </section>
        <section className="flex flex-col items-center w-2/4 max-md:w-full h-full justify-center">
          <div
            className="w-3/6 p-10 rounded-md dark:border-neutral-800 dark:bg-zinc-50/75 dark:from-inherit
                  max-2xl:w-4/6 
                  max-xl:w-full max-md:border-none max-md:rounded-none max-md:p-0 max-md:bg-transparent max-md:backdrop-blur-none max-md:dark:bg-transparent max-md:dark:backdrop-blur-none"
          >
            <Suspense fallback="Loading">{children}</Suspense>
          </div>
        </section>
      </main>
    </>
  );
}
